# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 02:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400)),
                ('created_time', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('emoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emoto_backend.Emoto')),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_code', models.TextField(max_length=6, null=True)),
                ('avatar', models.ImageField(null=True, upload_to='')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('city_cached', models.TextField(max_length=100)),
                ('weather_cached', models.TextField(max_length=100)),
                ('time_zone_cached', models.TextField(max_length=100)),
                ('temerature_cached', models.IntegerField()),
                ('weather_icon_url_cached', models.URLField(max_length=2000)),
                ('cache_timestamp', models.DateTimeField()),
                ('partner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recip_partner', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
