# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emoto_backend', '0003_auto_20160509_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emoto_backend.Profile', to_field='username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='partner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recip_partner', to='emoto_backend.Profile'),
        ),
    ]
