# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emoto_backend', '0004_auto_20160509_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='temerature_cached',
            new_name='temperature_cached',
        ),
    ]
