# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoto_backend', '0006_auto_20160509_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoto',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
