# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emoto_backend', '0007_emoto_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emoto',
            options={'ordering': ['name']},
        ),
    ]
