# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 05:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emoto_backend', '0009_auto_20160517_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_emoto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emoto_backend.Emoto'),
        ),
        migrations.AddField(
            model_name='profile',
            name='presence_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 17, 5, 19, 34, 610661)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
