# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoto_backend', '0011_auto_20160519_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='device_token',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
